"""empty message

Revision ID: 4516fd487e8c
Revises: 
Create Date: 2020-04-17 16:25:51.228564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4516fd487e8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_index('ix_creditors_full_name', table_name='creditors')
    op.drop_index('ix_creditors_idnumber', table_name='creditors')
    op.drop_table('creditors')
    op.drop_index('ix_users_full_name', table_name='users')
    op.drop_index('ix_users_idnumber', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_items_item_name', table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner', sa.INTEGER(), nullable=False),
    sa.Column('borrower', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['borrower'], ['creditors.idnumber'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.idnumber'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_items_item_name', 'items', ['item_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('idnumber', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.INTEGER(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_users_idnumber', 'users', ['idnumber'], unique=1)
    op.create_index('ix_users_full_name', 'users', ['full_name'], unique=False)
    op.create_table('creditors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('idnumber', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.INTEGER(), nullable=False),
    sa.Column('debt', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.idnumber'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_creditors_idnumber', 'creditors', ['idnumber'], unique=1)
    op.create_index('ix_creditors_full_name', 'creditors', ['full_name'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('creditorid', sa.INTEGER(), nullable=False),
    sa.Column('owner', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['creditorid'], ['creditors.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.idnumber'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
